modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
logoFile="logo.png"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[mixins]]
config="better_farming_radius.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# Requires the base mod. This addon mixes into it, so it must be loaded after it.
[[dependencies.${mod_id}]]
    modId="better_farming_plus"
    type="required"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
